import type { MigrationInterface, QueryRunner } from "typeorm";

export class SquashedBaseline1780280000000 implements MigrationInterface {
  name = "SquashedBaseline1780280000000";

  public async up(queryRunner: QueryRunner): Promise<void> {
    // Schema dumped at 2026-06-12T19:10:43.882Z
    // Generated by: pnpm db:migrate:squash
    await queryRunner.query(`CREATE TYPE public.ai_message_role AS ENUM (
    'User',
    'Assistant'
);`);

    await queryRunner.query(`CREATE TYPE public.application_source AS ENUM (
    'Linkedin',
    'Jack',
    'Wellfound',
    'RemoteYeah'
);`);

    await queryRunner.query(`CREATE TYPE public.application_stage AS ENUM (
    'Draft',
    'New',
    'Applied',
    'RecruiterScreen',
    'Technical',
    'CulturalFit',
    'Offer',
    'Rejected',
    'Duplicated'
);`);

    await queryRunner.query(`CREATE TYPE public.auth_provider AS ENUM (
    'Google'
);`);

    await queryRunner.query(`CREATE TYPE public.extension_activity_event_type AS ENUM (
    'SourceRunReceived',
    'SourceRunClaimSkipped',
    'SourceRunStarted',
    'SourceRunJobImported',
    'SourceRunCompleted',
    'SourceRunFailed',
    'ImportJobStarted',
    'ImportJobCompleted',
    'ImportJobFailed',
    'AuthRefreshed',
    'AuthFailed',
    'SourceRunPageCollected',
    'SourceRunStopConditionMet',
    'SourceRunJobSkipped',
    'SourceRunJobSurfaceImport',
    'SourceRunJobDetailsImport'
);`);

    await queryRunner.query(`CREATE TYPE public.fit_classification AS ENUM (
    'Positive',
    'Neutral',
    'Negative'
);`);

    await queryRunner.query(`CREATE TYPE public.role AS ENUM (
    'User',
    'Admin'
);`);

    await queryRunner.query(`CREATE TYPE public.salary_period AS ENUM (
    'Year',
    'Month',
    'Hour'
);`);

    await queryRunner.query(`CREATE TYPE public.source_run_status AS ENUM (
    'Pending',
    'Completed',
    'Failed'
);`);

    await queryRunner.query(`CREATE TYPE public.stage_event_source AS ENUM (
    'Manual',
    'System'
);`);

    await queryRunner.query(`CREATE TABLE public.ai_conversations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    job_id text NOT NULL,
    user_id text NOT NULL,
    title text DEFAULT 'New conversation'::text NOT NULL,
    generating_status jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`);

    await queryRunner.query(`CREATE TABLE public.ai_messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    conversation_id uuid NOT NULL,
    role public.ai_message_role NOT NULL,
    content text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);`);

    await queryRunner.query(`CREATE TABLE public.companies (
    id text NOT NULL,
    user_id text NOT NULL,
    name text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`);

    await queryRunner.query(`CREATE TABLE public.exchange_rate (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    base_currency text NOT NULL,
    rates_json jsonb NOT NULL,
    ttl_seconds integer NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`);

    await queryRunner.query(`CREATE TABLE public.extension_activity_events (
    id text NOT NULL,
    user_id text NOT NULL,
    type public.extension_activity_event_type NOT NULL,
    summary text NOT NULL,
    source_run_id text,
    payload jsonb,
    extension_version text,
    browser text,
    occurred_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);`);

    await queryRunner.query(`CREATE TABLE public.job_notes (
    id text NOT NULL,
    job_id text NOT NULL,
    user_id text NOT NULL,
    content text DEFAULT '{"type":"doc","content":[{"type":"paragraph"}]}'::text NOT NULL,
    revision integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`);

    await queryRunner.query(`CREATE TABLE public.job_stage_events (
    id text NOT NULL,
    job_id text NOT NULL,
    user_id text NOT NULL,
    from_stage public.application_stage,
    to_stage public.application_stage NOT NULL,
    source public.stage_event_source DEFAULT 'Manual'::public.stage_event_source NOT NULL,
    reason text,
    schedule_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);`);

    await queryRunner.query(`CREATE TABLE public.jobs (
    id text NOT NULL,
    user_id text NOT NULL,
    title text,
    company_id text,
    description text,
    urls text[] DEFAULT ARRAY[]::text[] NOT NULL,
    source public.application_source,
    salary_min_cents integer,
    salary_max_cents integer,
    salary_currency text,
    salary_period public.salary_period,
    tags text[] DEFAULT ARRAY[]::text[] NOT NULL,
    location text,
    work_region text,
    summary text,
    source_run_id text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    summary_status text,
    summary_error text,
    summary_timestamp timestamp with time zone,
    html_content text,
    fill_status text,
    fill_error text,
    fill_timestamp timestamp with time zone,
    stage public.application_stage DEFAULT 'New'::public.application_stage NOT NULL,
    published_at timestamp with time zone
);`);

    await queryRunner.query(`CREATE TABLE public.match_analysis (
    id text NOT NULL,
    job_id text NOT NULL,
    user_id text,
    resume_id text NOT NULL,
    score_ratio double precision,
    classification public.fit_classification,
    fit_count integer DEFAULT 0 NOT NULL,
    gap_count integer DEFAULT 0 NOT NULL,
    unclear_count integer DEFAULT 0 NOT NULL,
    items jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    generation_status text,
    generation_error text,
    generation_timestamp timestamp with time zone
);`);

    await queryRunner.query(`CREATE TABLE public.plans (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    display_name character varying(256) NOT NULL,
    document jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id text NOT NULL
);`);

    await queryRunner.query(`CREATE TABLE public.resumes (
    id text NOT NULL,
    user_id text NOT NULL,
    title text NOT NULL,
    content text DEFAULT '{"type":"doc","content":[{"type":"paragraph"}]}'::text NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`);

    await queryRunner.query(`CREATE TABLE public.source_runs (
    id text NOT NULL,
    user_id text NOT NULL,
    template_id text NOT NULL,
    surface_url text NOT NULL,
    status public.source_run_status DEFAULT 'Pending'::public.source_run_status NOT NULL,
    started_at timestamp with time zone NOT NULL,
    error_message text
);`);

    await queryRunner.query(`CREATE TABLE public.source_templates (
    id text NOT NULL,
    user_id text NOT NULL,
    schedule_cron text,
    schedule_enabled boolean DEFAULT false NOT NULL,
    surface_url text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    plan_id uuid NOT NULL,
    config jsonb
);`);

    await queryRunner.query(`CREATE TABLE public.user_accounts (
    id text NOT NULL,
    user_id text NOT NULL,
    provider_name public.auth_provider NOT NULL,
    provider_account_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);`);

    await queryRunner.query(`CREATE TABLE public.user_settings (
    user_id text NOT NULL,
    auto_fill_enabled boolean DEFAULT false NOT NULL,
    auto_summary_enabled boolean DEFAULT false NOT NULL,
    duplicate_window_days integer DEFAULT 30 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    auto_match_enabled boolean DEFAULT false NOT NULL,
    blocked_keywords jsonb DEFAULT '[]'::jsonb NOT NULL,
    blocked_companies jsonb DEFAULT '[]'::jsonb NOT NULL
);`);

    await queryRunner.query(`CREATE TABLE public.users (
    id text NOT NULL,
    email text NOT NULL,
    name text NOT NULL,
    avatar_url text,
    role public.role DEFAULT 'User'::public.role NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    active boolean DEFAULT true NOT NULL,
    token_version integer DEFAULT 0 NOT NULL,
    refresh_jti uuid
);`);

    await queryRunner.query(`CREATE TABLE public.work_preferences (
    id text NOT NULL,
    user_id text NOT NULL,
    items jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);`);

    await queryRunner.query(`ALTER TABLE ONLY public.plans
    ADD CONSTRAINT "PK_plans" PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.user_accounts
    ADD CONSTRAINT "PK_user_accounts" PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.user_accounts
    ADD CONSTRAINT "UQ_user_accounts_provider_subject" UNIQUE (provider_name, provider_account_id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.job_notes
    ADD CONSTRAINT job_notes_pkey PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.job_stage_events
    ADD CONSTRAINT job_stage_events_pkey PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.match_analysis
    ADD CONSTRAINT match_analysis_pkey PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.ai_conversations
    ADD CONSTRAINT pk_ai_conversations PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.ai_messages
    ADD CONSTRAINT pk_ai_messages PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.exchange_rate
    ADD CONSTRAINT pk_exchange_rate PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.extension_activity_events
    ADD CONSTRAINT pk_extension_activity_events_id PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT pk_user_settings_user_id PRIMARY KEY (user_id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.resumes
    ADD CONSTRAINT resumes_pkey PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.source_runs
    ADD CONSTRAINT source_runs_pkey PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.source_templates
    ADD CONSTRAINT source_templates_pkey PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.exchange_rate
    ADD CONSTRAINT uq_exchange_rate_base_currency UNIQUE (base_currency);`);

    await queryRunner.query(`ALTER TABLE ONLY public.match_analysis
    ADD CONSTRAINT uq_match_analysis_job_id UNIQUE (job_id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.users
    ADD CONSTRAINT uq_users_email UNIQUE (email);`);

    await queryRunner.query(`ALTER TABLE ONLY public.work_preferences
    ADD CONSTRAINT uq_work_preferences_user_id UNIQUE (user_id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.work_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);`);

    await queryRunner.query(`CREATE INDEX "IDX_user_accounts_user_id" ON public.user_accounts USING btree (user_id);`);

    await queryRunner.query(
      `CREATE INDEX idx_ai_conversations_job_id ON public.ai_conversations USING btree (job_id);`,
    );

    await queryRunner.query(
      `CREATE INDEX idx_ai_conversations_user_id ON public.ai_conversations USING btree (user_id);`,
    );

    await queryRunner.query(
      `CREATE INDEX idx_ai_messages_conversation_id ON public.ai_messages USING btree (conversation_id);`,
    );

    await queryRunner.query(
      `CREATE INDEX idx_extension_activity_events_user_occurred ON public.extension_activity_events USING btree (user_id, occurred_at DESC);`,
    );

    await queryRunner.query(`CREATE INDEX idx_jobs_source_run ON public.jobs USING btree (source_run_id);`);

    await queryRunner.query(
      `CREATE INDEX idx_source_runs_template_started ON public.source_runs USING btree (template_id, started_at DESC);`,
    );

    await queryRunner.query(
      `CREATE INDEX idx_source_runs_user_started ON public.source_runs USING btree (user_id, started_at DESC);`,
    );

    await queryRunner.query(`CREATE INDEX idx_source_templates_user ON public.source_templates USING btree (user_id);`);

    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_companies_user_lower_name ON public.companies USING btree (user_id, lower(TRIM(BOTH FROM name)));`,
    );

    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_source_templates_user_plan ON public.source_templates USING btree (user_id, plan_id);`,
    );

    await queryRunner.query(`ALTER TABLE ONLY public.user_accounts
    ADD CONSTRAINT "FK_user_accounts_user_id" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.job_notes
    ADD CONSTRAINT fk_an_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.job_stage_events
    ADD CONSTRAINT fk_ase_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.companies
    ADD CONSTRAINT fk_companies_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.extension_activity_events
    ADD CONSTRAINT fk_extension_activity_events_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.job_notes
    ADD CONSTRAINT fk_jn_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs_company_id FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs_source_run FOREIGN KEY (source_run_id) REFERENCES public.source_runs(id) ON DELETE SET NULL;`);

    await queryRunner.query(`ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT fk_jobs_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.job_stage_events
    ADD CONSTRAINT fk_jse_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.match_analysis
    ADD CONSTRAINT fk_ma_job_id FOREIGN KEY (job_id) REFERENCES public.jobs(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.match_analysis
    ADD CONSTRAINT fk_ma_resume_id FOREIGN KEY (resume_id) REFERENCES public.resumes(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.match_analysis
    ADD CONSTRAINT fk_ma_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.plans
    ADD CONSTRAINT fk_plans_user_id FOREIGN KEY (user_id) REFERENCES public.users(id);`);

    await queryRunner.query(`ALTER TABLE ONLY public.resumes
    ADD CONSTRAINT fk_resumes_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.source_runs
    ADD CONSTRAINT fk_source_runs_template_id FOREIGN KEY (template_id) REFERENCES public.source_templates(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.source_templates
    ADD CONSTRAINT fk_source_templates_plan_id FOREIGN KEY (plan_id) REFERENCES public.plans(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.work_preferences
    ADD CONSTRAINT fk_user_preferences_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;`);

    await queryRunner.query(`ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT fk_user_settings_user_id FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;`);
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {
    // Intentionally empty: squashed baseline migration is not reversible.
  }
}
