#!/usr/bin/env node

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, "..");
const specsDir = path.join(repoRoot, "specs");
const outDir = path.join(repoRoot, "docs", "specs");

function humanizeSlug(slug: string): string {
  const rest = slug.replace(/^\d{3}-/, "");
  return rest
    .split("-")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

function mdxForImport(
  metaTitle: string,
  importPath: string,
  sourceFile: string,
): string {
  return `import { Meta } from "@storybook/addon-docs/blocks";

import { SpecMarkdown } from "@ui/stories/spec-markdown";
import raw from "${importPath}?raw";

<Meta title="${metaTitle}" />

<SpecMarkdown raw={raw} sourceFile="${sourceFile}" />
`;
}

function writeIfChanged(filePath: string, next: string): boolean {
  const prev = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : "";
  if (prev !== next) {
    fs.writeFileSync(filePath, next, "utf8");
    return true;
  }
  return false;
}

function main(): void {
  execFileSync(
    process.execPath,
    [
      "--experimental-strip-types",
      path.join(repoRoot, "scripts/generate-requirement-id-map.ts"),
    ],
    { cwd: repoRoot, stdio: "inherit" },
  );

  fs.mkdirSync(outDir, { recursive: true });

  const banner = `{/* Generated by scripts/generate-specs-storybook.ts — do not edit by hand */}\n\n`;

  let changed = 0;

  const rootFiles = [
    {
      out: "OVERVIEW.mdx",
      specRel: "README.md",
      relImport: "../../specs/README.md",
      sourceFile: "specs/README.md",
      title: "Documentation/Specs/Overview",
    },
    {
      out: "HISTORY.mdx",
      specRel: "HISTORY.md",
      relImport: "../../specs/HISTORY.md",
      sourceFile: "specs/HISTORY.md",
      title: "Documentation/Specs/History",
    },
    {
      out: "INDEX.mdx",
      specRel: "INDEX.md",
      relImport: "../../specs/INDEX.md",
      sourceFile: "specs/INDEX.md",
      title: "Documentation/Specs/Generated index",
    },
  ];

  for (const { out, specRel, relImport, sourceFile, title } of rootFiles) {
    const abs = path.join(specsDir, specRel);
    if (!fs.existsSync(abs)) {
      console.warn(`skip (missing): ${abs}`);
      continue;
    }
    const body = banner + mdxForImport(title, relImport, sourceFile);
    if (writeIfChanged(path.join(outDir, out), body)) changed++;
  }

  const entries = fs.readdirSync(specsDir, { withFileTypes: true });
  const slugRe = /^\d{3}-[a-z0-9-]+$/;

  for (const ent of entries) {
    if (!ent.isDirectory() || !slugRe.test(ent.name)) continue;
    const readme = path.join(specsDir, ent.name, "README.md");
    if (!fs.existsSync(readme)) continue;

    const id = ent.name.slice(0, 3);
    const human = humanizeSlug(ent.name);
    const title = `Documentation/Specs/${id} — ${human}`;
    const outName = `${ent.name}.mdx`;
    const relImport = `../../specs/${ent.name}/README.md`;
    const sourceFile = `specs/${ent.name}/README.md`;
    const body = banner + mdxForImport(title, relImport, sourceFile);
    if (writeIfChanged(path.join(outDir, outName), body)) changed++;
  }

  console.log(
    `generate-specs-storybook: ${changed} file(s) updated under docs/specs/`,
  );
}

main();
