query DraftApplicationsList {
  draftApplications {
    id
    applicationId
    url
    title
    conversionStatus
    conversionError
  }
}

query DraftApplicationDetail($id: ID!) {
  draftApplication(id: $id) {
    id
    applicationId
    url
    title
    htmlContent
    conversionStatus
    conversionError
  }
}

mutation DeleteDraftApplication($id: ID!, $deleteLinkedApplication: Boolean) {
  deleteDraftApplication(
    id: $id
    deleteLinkedApplication: $deleteLinkedApplication
  ) {
    success
    deletedId
  }
}

mutation DeleteApplicationsForDraft($draftId: ID!) {
  deleteApplicationsForDraft(draftId: $draftId) {
    success
    deletedId
  }
}

mutation CreateApplicationWithAiV2($draftId: ID!) {
  createApplicationWithAIV2(draftId: $draftId) {
    id
    title
    conversionStatus
    conversionError
  }
}

mutation CreateDraftApplication($input: CreateDraftApplicationInput!) {
  createDraftApplication(input: $input) {
    id
    applicationId
    url
    title
    conversionStatus
    conversionError
  }
}

mutation UpdateDraftApplication(
  $id: ID!
  $input: UpdateDraftApplicationInput!
) {
  updateDraftApplication(id: $id, input: $input) {
    id
    applicationId
    url
    title
    conversionStatus
    conversionError
  }
}
