query ImportersList {
  importers(onlyWithImportTemplate: true) {
    importerId
    name
  }
}

query ImportersForNewImportTemplatePicker {
  importers(onlyWithImportTemplate: false) {
    importerId
    name
  }
}

query ImportTemplatesForImporter($importerId: String!) {
  importTemplatesForImporter(importerId: $importerId) {
    id
    importerId
    scheduleCron
    scheduleEnabled
    surfaceUrl
    createdAt
    runs {
      id
      status
      startedAt
    }
  }
}

mutation UpdateImportTemplate($id: ID!, $input: UpdateImportTemplateInput!) {
  updateImportTemplate(id: $id, input: $input) {
    id
    importerId
    scheduleCron
    scheduleEnabled
    surfaceUrl
    createdAt
    runs {
      id
      status
      startedAt
    }
  }
}

mutation DeleteImportTemplate($id: ID!) {
  deleteImportTemplate(id: $id) {
    success
    deletedId
  }
}

mutation CreateImportTemplate($input: CreateImportTemplateInput!) {
  createImportTemplate(input: $input) {
    id
    importerId
    surfaceUrl
    scheduleCron
    scheduleEnabled
    createdAt
  }
}
