query SourceProfilesList {
  sourceProfiles(onlyWithSourceTemplate: true) {
    sourceProfileId
    name
  }
}

query SourceProfilesListAll {
  sourceProfiles {
    sourceProfileId
    name
  }
}

mutation RerunSourceTemplate($templateId: ID!) {
  rerunSourceTemplate(templateId: $templateId) {
    id
    status
    startedAt
    surfaceUrl
    sourceProfileId
  }
}

mutation DeleteSourceRun($id: ID!, $deleteJobs: Boolean = false) {
  deleteSourceRun(id: $id, deleteJobs: $deleteJobs) {
    success
    deletedId
  }
}

query SourceTemplate($id: ID!) {
  sourceTemplate(id: $id) {
    id
    sourceProfileId
    scheduleCron
    scheduleEnabled
    surfaceUrl
    createdAt
    runs {
      id
      status
      startedAt
    }
  }
}

query SourcesForSourceProfile($sourceProfileId: String!) {
  sourceTemplatesForSourceProfile(sourceProfileId: $sourceProfileId) {
    id
    sourceProfileId
    scheduleCron
    scheduleEnabled
    surfaceUrl
    createdAt
    runs {
      id
      status
      startedAt
    }
  }
}

mutation UpdateSourceTemplate($id: ID!, $input: UpdateSourceTemplateInput!) {
  updateSourceTemplate(id: $id, input: $input) {
    id
    sourceProfileId
    scheduleCron
    scheduleEnabled
    surfaceUrl
    createdAt
    runs {
      id
      status
      startedAt
    }
  }
}

mutation DeleteSourceTemplate($id: ID!) {
  deleteSourceTemplate(id: $id) {
    success
    deletedId
  }
}

mutation CreateSourceTemplate($input: CreateSourceTemplateInput!) {
  createSourceTemplate(input: $input) {
    id
    sourceProfileId
    surfaceUrl
    scheduleCron
    scheduleEnabled
    createdAt
  }
}

query Plans {
  plans {
    id
    sourceProfileId
    displayName
  }
}

query Plan($sourceProfileId: String!) {
  plan(sourceProfileId: $sourceProfileId) {
    id
    sourceProfileId
    displayName
    document
    createdAt
    updatedAt
  }
}

mutation UpdatePlan($id: ID!, $input: UpdatePlanInput!) {
  updatePlan(id: $id, input: $input) {
    id
    sourceProfileId
    displayName
    document
    updatedAt
  }
}

mutation CreatePlan($input: CreatePlanInput!) {
  createPlan(input: $input) {
    id
    sourceProfileId
    displayName
    document
    createdAt
    updatedAt
  }
}
