query SourceProfilesList {
  sourceProfiles(onlyWithSourceTemplate: true) {
    sourceProfileId
    name
  }
}

query SourceProfilesForNewSourcePicker {
  sourceProfiles(onlyWithSourceTemplate: false) {
    sourceProfileId
    name
  }
}

query SourcesForSourceProfile($sourceProfileId: String!) {
  sourceTemplatesForSourceProfile(sourceProfileId: $sourceProfileId) {
    id
    sourceProfileId
    scheduleCron
    scheduleEnabled
    surfaceUrl
    createdAt
    runs {
      id
      status
      startedAt
    }
  }
}

mutation UpdateSourceTemplate($id: ID!, $input: UpdateSourceTemplateInput!) {
  updateSourceTemplate(id: $id, input: $input) {
    id
    sourceProfileId
    scheduleCron
    scheduleEnabled
    surfaceUrl
    createdAt
    runs {
      id
      status
      startedAt
    }
  }
}

mutation DeleteSourceTemplate($id: ID!) {
  deleteSourceTemplate(id: $id) {
    success
    deletedId
  }
}

mutation CreateSourceTemplate($input: CreateSourceTemplateInput!) {
  createSourceTemplate(input: $input) {
    id
    sourceProfileId
    surfaceUrl
    scheduleCron
    scheduleEnabled
    createdAt
  }
}
